### DISCUSSION TITLE
Single Servo Module

### DISCUSSION THREAD

**Discussion by danic85** [makerforgetech/modular-biped#125] [Ideas]
The current develop branch now has three main modules for managing servos:
- `modules/actuators/servo.py`: for servo communication via UART to the `arduino_sketch`
- `modules/actuators/piservo.py`: for servo communication via GPIO from the Raspberry Pi.
- `modules/i2c_servo.py`: for servo communication via I2C using the servo driver board PCA9685

I'd like to merge all three, into the main `servo.py` file, so that a protocol can be selected for each servo instance.

We already support multiple servos on a single module:

```
servos:
  enabled: false
  path: "modules.actuators.servo.Servo" # Include class name here
  instances:
    - name: "leg_l_hip"
      id: 0
      pin: 9
      range: [0, 180]
      start: 40
    - name: "leg_l_knee"
      id: 1
      pin: 10
      range: [0, 180]
      start: 10
```

This change would allow each servo instance to have a `protocol` attribute which would determine which logic to use, and combine all protocols into a single module.

The piServo and i2cServo modules are very simple, and so can be merged easily.

To reduce complexity and improve readability, there should be a hierarchy of modules:

Create a BaseServo module that handles generic functionality, such as calculating angles from percentages and storing values. Extend with three classes for UARTServo, GPIOServo (formerly PiServo) and I2CServo.

The module loader may also need to be modified to support this.

**Comment by danic85** [comment]
Created https://github.com/makerforgetech/modular-biped/tree/feature/servo_module as a starting point for this. It has not been tested.

The I2C servo module handles multiple servos with a single instance, but the other servo modules do not. This needs to be standardised.

I have attempted to manage the protocol changes by creating three configuration items in the servo.yaml. The module loader should be able to handle this correctly (untested).

```
uart_servos:
  enabled: false
  path: "modules.actuators.uart_servo.UARTServo" # Include class name here
  instances:
    - name: "leg_l_hip"
      id: 0
      pin: 9
      range: [0, 180]
      start: 40
    - name: "leg_l_knee"
      id: 1
      pin: 10
      range: [0, 180]
      start: 10
    - name: "leg_l_ankle"
      id: 2
      pin: 11
      range: [5, 165]
      start: 100
    - name: "leg_r_hip"
      id: 3
      pin: 6
      range: [0, 180]
      start: 60
    - name: "leg_r_knee"
      id: 4
      pin: 7
      range: [0, 180]
      start: 90
    - name: "leg_r_ankle"
      id: 5
      pin: 8
      range: [10, 180]
      start: 0
    - name: "tilt"
      id: 6
      pin: 2
      range: [60, 120]
      start: 50
    - name: "pan"
      id: 7
      pin: 3
      range: [30, 150]
      start: 50
  dependencies:
    python:
      - pigpio

gpio_servos:
  enabled: false
  path: "modules.actuators.gpio_servo.GPIOServo" # Include class name here
  instances:
    - name: "ear"
      id: 0
      pin: 12 
      range: [-40, 40]
      start: 0
  dependencies:
    python:
      - gpiozero

i2c_servos:
  enabled: false
  path: modules.i2c_servo.I2CServo
  config:
    test_on_boot: false
    servo_count: 16
  dependencies:
    unix:
      - python3-smbus
    python:
      - adafruit-circuitpython-servokit
```
